### ISSUE TITLE
Errors when running otx2crits

### ISSUE THREAD

**Issue by cvdsouza** [Magicked/otx2crits#1]
Hi, 
Not sure if you're still working on this. 

-> One suggestion for references under the execute() 

reference =''
            if not reference:

                reference = 'No reference documented'
            else:
                reference = pulse['references'][0]
This should ensure that if no references are documented then it doesn't throw an index out of bounds. 

Additionally, I get the following error , which I'm not sure about : 

Traceback (most recent call last):
  File "otx2crits.py", line 389, in <module>
    main()
  File "otx2crits.py", line 385, in main
    otx2crits.execute()
  File "otx2crits.py", line 69, in execute
    pulse['name']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 19: ordinal not in range(128)

still looking into debugging it , thought would get your insight as well if you are still working on this code.

**Comment by cvdsouza** [comment]
Looks like I needed to add : .encode("utf-8") to certain parameters and that fixed the issue.

**Comment by lolnate** [comment]
Hey, thanks for looking into this. If you wrote a fix in the otx2crits code, do you mind submitting a PR with the changes (or just write here where you put the .encode("utf-8")?

**Comment by cvdsouza** [comment]
I wrote a fix to get it working for me. I'll submit a PR for your review.
